# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baccarat.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class BaccaratWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1385, 895)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-4, -8, 1391, 881))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("baccarat.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.balanceLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.balanceLabel.setGeometry(QtCore.QRect(500, 740, 351, 131))
        self.balanceLabel.setStyleSheet("QLineEdit {\n"
"background-color: transparent;\n"
"color: #fff;\n"
"font-size: 20px;\n"
"border-radius: 20px;\n"
"border: 2px solid #222222;\n"
"padding: auto;\n"
"}")
        self.balanceLabel.setText("")
        self.balanceLabel.setReadOnly(True)
        self.balanceLabel.setObjectName("balanceLabel")
        self.dealerButton = QtWidgets.QPushButton(self.centralwidget)
        self.dealerButton.setGeometry(QtCore.QRect(500, 630, 111, 111))
        self.dealerButton.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.dealerButton.setObjectName("dealerButton")
        self.playerButton = QtWidgets.QPushButton(self.centralwidget)
        self.playerButton.setGeometry(QtCore.QRect(740, 630, 111, 111))
        self.playerButton.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.playerButton.setObjectName("playerButton")
        self.tieButton = QtWidgets.QPushButton(self.centralwidget)
        self.tieButton.setGeometry(QtCore.QRect(620, 630, 111, 111))
        self.tieButton.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.tieButton.setObjectName("tieButton")
        self.dealerCard1 = QtWidgets.QLabel(self.centralwidget)
        self.dealerCard1.setGeometry(QtCore.QRect(200, 420, 81, 121))
        self.dealerCard1.setObjectName("dealerCard1")
        self.dealerCard2 = QtWidgets.QLabel(self.centralwidget)
        self.dealerCard2.setGeometry(QtCore.QRect(280, 420, 81, 121))
        self.dealerCard2.setObjectName("dealerCard2")
        self.dealerCard3 = QtWidgets.QLabel(self.centralwidget)
        self.dealerCard3.setGeometry(QtCore.QRect(360, 420, 81, 121))
        self.dealerCard3.setObjectName("dealerCard3")
        self.playerCard1 = QtWidgets.QLabel(self.centralwidget)
        self.playerCard1.setGeometry(QtCore.QRect(930, 420, 81, 121))
        self.playerCard1.setObjectName("playerCard1")
        self.playerCard3 = QtWidgets.QLabel(self.centralwidget)
        self.playerCard3.setGeometry(QtCore.QRect(1090, 420, 81, 121))
        self.playerCard3.setObjectName("playerCard3")
        self.playerCard2 = QtWidgets.QLabel(self.centralwidget)
        self.playerCard2.setGeometry(QtCore.QRect(1010, 420, 81, 121))
        self.playerCard2.setObjectName("playerCard2")
        self.resultLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(480, 50, 581, 71))
        self.resultLabel.setStyleSheet("QLineEdit {\n"
"background-color: transparent;\n"
"font-size: 30px;\n"
"font-weight: 800;\n"
"border: none;\n"
"color: #C8C8C8;\n"
"}")
        self.resultLabel.setReadOnly(True)
        self.resultLabel.setObjectName("resultLabel")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 20, 131, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    font-size: 25px;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(200, 10, 121, 61))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(250, 340, 141, 51))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"background-color: transparent;\n"
"color: #c8c8c8;\n"
"border: none;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(990, 340, 141, 51))
        self.textEdit_2.setStyleSheet("QTextEdit {\n"
"background-color: transparent;\n"
"color: #c8c8c8;\n"
"border: none;\n"
"font-size: 20px\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.newGameButton = QtWidgets.QPushButton(self.centralwidget)
        self.newGameButton.setGeometry(QtCore.QRect(860, 630, 161, 251))
        self.newGameButton.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.newGameButton.setObjectName("newGameButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1385, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dealerButton.setText(_translate("MainWindow", "Dealer"))
        self.playerButton.setText(_translate("MainWindow", "Player"))
        self.tieButton.setText(_translate("MainWindow", "Tie (8X)"))
        self.dealerCard1.setText(_translate("MainWindow", "l"))
        self.dealerCard2.setText(_translate("MainWindow", "l"))
        self.dealerCard3.setText(_translate("MainWindow", "l"))
        self.playerCard1.setText(_translate("MainWindow", "l"))
        self.playerCard3.setText(_translate("MainWindow", "l"))
        self.playerCard2.setText(_translate("MainWindow", "l"))
        self.pushButton_3.setText(_translate("MainWindow", "𝐎𝐑𝐎𝐒𝐍𝐄𝐁𝐈"))
        self.pushButton_5.setText(_translate("MainWindow", "Blackjack"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">Dealer</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">Player</span></p></body></html>"))
        self.newGameButton.setText(_translate("MainWindow", "New Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = BaccaratWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())