# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blackjack.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class BlackjackWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1385, 895)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-4, -8, 1391, 881))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bj.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.hitButton = QtWidgets.QPushButton(self.centralwidget)
        self.hitButton.setGeometry(QtCore.QRect(520, 670, 75, 61))
        self.hitButton.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.hitButton.setObjectName("hitButton")
        self.standButton = QtWidgets.QPushButton(self.centralwidget)
        self.standButton.setGeometry(QtCore.QRect(640, 670, 75, 61))
        self.standButton.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.standButton.setObjectName("standButton")
        self.splitButton = QtWidgets.QPushButton(self.centralwidget)
        self.splitButton.setGeometry(QtCore.QRect(760, 670, 75, 61))
        self.splitButton.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.splitButton.setObjectName("splitButton")
        self.balanceLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.balanceLabel.setGeometry(QtCore.QRect(520, 740, 311, 131))
        self.balanceLabel.setStyleSheet("QLineEdit {\n"
"background-color: transparent;\n"
"color: #fff;\n"
"font-size: 20px;\n"
"border-radius: 20px;\n"
"border: 2px solid #222222;\n"
"padding: auto;\n"
"}")
        self.balanceLabel.setText("")
        self.balanceLabel.setReadOnly(True)
        self.balanceLabel.setObjectName("balanceLabel")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(320, 10, 121, 61))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 20, 131, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    font-size: 25px;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 10, 121, 61))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.playerCard1 = QtWidgets.QLabel(self.centralwidget)
        self.playerCard1.setGeometry(QtCore.QRect(580, 490, 91, 131))
        self.playerCard1.setText("")
        self.playerCard1.setObjectName("playerCard1")
        self.playerCard2 = QtWidgets.QLabel(self.centralwidget)
        self.playerCard2.setGeometry(QtCore.QRect(670, 490, 91, 131))
        self.playerCard2.setText("")
        self.playerCard2.setObjectName("playerCard2")
        self.dealerCard1 = QtWidgets.QLabel(self.centralwidget)
        self.dealerCard1.setGeometry(QtCore.QRect(560, 70, 91, 131))
        self.dealerCard1.setText("")
        self.dealerCard1.setObjectName("dealerCard1")
        self.dealerCard2 = QtWidgets.QLabel(self.centralwidget)
        self.dealerCard2.setGeometry(QtCore.QRect(650, 70, 91, 131))
        self.dealerCard2.setText("")
        self.dealerCard2.setObjectName("dealerCard2")
        self.resultLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(430, 270, 581, 71))
        self.resultLabel.setStyleSheet("QLineEdit {\n"
"background-color: transparent;\n"
"font-size: 30px;\n"
"font-weight: 800;\n"
"border: none;\n"
"color: #C8C8C8;\n"
"}")
        self.resultLabel.setReadOnly(True)
        self.resultLabel.setObjectName("resultLabel")
        self.playerCard3 = QtWidgets.QLabel(self.centralwidget)
        self.playerCard3.setGeometry(QtCore.QRect(760, 490, 91, 131))
        self.playerCard3.setText("")
        self.playerCard3.setObjectName("playerCard3")
        self.playerCard4 = QtWidgets.QLabel(self.centralwidget)
        self.playerCard4.setGeometry(QtCore.QRect(850, 490, 91, 131))
        self.playerCard4.setText("")
        self.playerCard4.setObjectName("playerCard4")
        self.dealerCard3 = QtWidgets.QLabel(self.centralwidget)
        self.dealerCard3.setGeometry(QtCore.QRect(740, 70, 91, 131))
        self.dealerCard3.setText("")
        self.dealerCard3.setObjectName("dealerCard3")
        self.dealerCard4 = QtWidgets.QLabel(self.centralwidget)
        self.dealerCard4.setGeometry(QtCore.QRect(830, 70, 91, 131))
        self.dealerCard4.setText("")
        self.dealerCard4.setObjectName("dealerCard4")
        self.splittedCard3 = QtWidgets.QLabel(self.centralwidget)
        self.splittedCard3.setGeometry(QtCore.QRect(760, 360, 91, 131))
        self.splittedCard3.setText("")
        self.splittedCard3.setObjectName("splittedCard3")
        self.splittedCard1 = QtWidgets.QLabel(self.centralwidget)
        self.splittedCard1.setGeometry(QtCore.QRect(580, 360, 91, 131))
        self.splittedCard1.setText("")
        self.splittedCard1.setScaledContents(False)
        self.splittedCard1.setObjectName("splittedCard1")
        self.splittedCard4 = QtWidgets.QLabel(self.centralwidget)
        self.splittedCard4.setGeometry(QtCore.QRect(850, 360, 91, 131))
        self.splittedCard4.setText("")
        self.splittedCard4.setObjectName("splittedCard4")
        self.splittedCard2 = QtWidgets.QLabel(self.centralwidget)
        self.splittedCard2.setGeometry(QtCore.QRect(670, 360, 91, 131))
        self.splittedCard2.setText("")
        self.splittedCard2.setObjectName("splittedCard2")
        self.newGameButton = QtWidgets.QPushButton(self.centralwidget)
        self.newGameButton.setGeometry(QtCore.QRect(860, 760, 131, 61))
        self.newGameButton.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.newGameButton.setObjectName("newGameButton")
        self.resultLabel_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.resultLabel_2.setGeometry(QtCore.QRect(520, 230, 581, 71))
        self.resultLabel_2.setStyleSheet("QLineEdit {\n"
"background-color: transparent;\n"
"font-size: 30px;\n"
"font-weight: 800;\n"
"border: none;\n"
"color: #C8C8C8;\n"
"}")
        self.resultLabel_2.setReadOnly(True)
        self.resultLabel_2.setObjectName("resultLabel_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1385, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hitButton.setText(_translate("MainWindow", "Hit"))
        self.standButton.setText(_translate("MainWindow", "Stand"))
        self.splitButton.setText(_translate("MainWindow", "Split"))
        self.pushButton_5.setText(_translate("MainWindow", "Blackjack"))
        self.pushButton_3.setText(_translate("MainWindow", "𝐎𝐑𝐎𝐒𝐍𝐄𝐁𝐈"))
        self.pushButton_6.setText(_translate("MainWindow", "Baccarat"))
        self.newGameButton.setText(_translate("MainWindow", "New Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = BlackjackWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())