# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'casino_lobby.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from casino import Ui_MainWindow


class Ui_OtherWindow(object):
    def setupUi(self, OtherWindow):
        OtherWindow.setObjectName("OtherWindow")
        OtherWindow.resize(1389, 897)
        self.centralwidget = QtWidgets.QWidget(OtherWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-4, -7, 1391, 881))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("raw.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 10, 121, 61))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1280, 0, 91, 81))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 10, 121, 61))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 20, 131, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    font-size: 25px;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1130, 0, 141, 81))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        OtherWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OtherWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1389, 21))
        self.menubar.setObjectName("menubar")
        OtherWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OtherWindow)
        self.statusbar.setObjectName("statusbar")
        OtherWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OtherWindow)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow)

    def retranslateUi(self, OtherWindow):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow.setWindowTitle(_translate("OtherWindow", "OtherWindow"))
        self.pushButton_5.setText(_translate("OtherWindow", "Baccarat"))
        self.pushButton_2.setText(_translate("OtherWindow", "Login"))
        self.pushButton_4.setText(_translate("OtherWindow", "Blackjack"))
        self.pushButton_3.setText(_translate("OtherWindow", "𝐎𝐑𝐎𝐒𝐍𝐄𝐁𝐈"))
        self.pushButton_6.setText(_translate("OtherWindow", "Registration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtherWindow = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow()
    ui.setupUi(OtherWindow)
    OtherWindow.show()
    sys.exit(app.exec_())
