# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1385, 895)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1391, 871))
        self.label.setAutoFillBackground(True)
        self.label.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bj.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 450, 351, 51))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(53, 53, 53, 0.6);\n"
"    opacity: 0.5;\n"
"    border: 2px solid #222222;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 16px;\n"
"    color: #eeeeee;\n"
"    selection-background-color: #00ff99;\n"
"    transition: all 2s ease-in-out;\n"
"}\n"
"\n"
"/* Hover effect: sleek green outline */\n"
"QLineEdit:hover {\n"
"    border: 2px solid #00cc66;\n"
"}\n"
"\n"
"/* Focus effect: sharp green glow */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00ff88;\n"
"    box-shadow: 0 0 6px #00ff88;\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    outline: none;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(850, 390, 351, 51))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(53, 53, 53, 0.6);\n"
"    opacity: 0.5;\n"
"    border: 2px solid #222222;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 16px;\n"
"    color: #eeeeee;\n"
"    selection-background-color: #00ff99;\n"
"    transition: all 2s ease-in-out;\n"
"}\n"
"\n"
"/* Hover effect: sleek green outline */\n"
"QLineEdit:hover {\n"
"    border: 2px solid #00cc66;\n"
"}\n"
"\n"
"/* Focus effect: sharp green glow */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00ff88;\n"
"    box-shadow: 0 0 6px #00ff88;\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    outline: none;\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 390, 351, 51))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(53, 53, 53, 0.6);\n"
"    opacity: 0.5;\n"
"    border: 2px solid #222222;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 16px;\n"
"    color: #eeeeee;\n"
"    selection-background-color: #00ff99;\n"
"    transition: all 2s ease-in-out;\n"
"}\n"
"\n"
"/* Hover effect: sleek green outline */\n"
"QLineEdit:hover {\n"
"    border: 2px solid #00cc66;\n"
"}\n"
"\n"
"/* Focus effect: sharp green glow */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00ff88;\n"
"    box-shadow: 0 0 6px #00ff88;\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    outline: none;\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(470, 90, 451, 151))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"    background-color: transparent;\n"
"    border: transparent;\n"
"    text-align: center;\n"
"    padding: 40% 50%;\n"
"    color: #222222;\n"
"    font-family: \'Consolas\', \'Courier New\', monospace;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 510, 351, 51))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(53, 53, 53, 0.6);\n"
"    opacity: 0.5;\n"
"    border: 2px solid #222222;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 16px;\n"
"    color: #eeeeee;\n"
"    selection-background-color: #00ff99;\n"
"    transition: all 2s ease-in-out;\n"
"}\n"
"\n"
"/* Hover effect: sleek green outline */\n"
"QLineEdit:hover {\n"
"    border: 2px solid #00cc66;\n"
"}\n"
"\n"
"/* Focus effect: sharp green glow */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00ff88;\n"
"    box-shadow: 0 0 6px #00ff88;\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    outline: none;\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(850, 450, 351, 51))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(53, 53, 53, 0.6);\n"
"    opacity: 0.5;\n"
"    border: 2px solid #222222;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 16px;\n"
"    color: #eeeeee;\n"
"    selection-background-color: #00ff99;\n"
"    transition: all 2s ease-in-out;\n"
"}\n"
"\n"
"/* Hover effect: sleek green outline */\n"
"QLineEdit:hover {\n"
"    border: 2px solid #00cc66;\n"
"}\n"
"\n"
"/* Focus effect: sharp green glow */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00ff88;\n"
"    box-shadow: 0 0 6px #00ff88;\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    outline: none;\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(850, 510, 351, 51))
        self.lineEdit_6.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(53, 53, 53, 0.6);\n"
"    opacity: 0.5;\n"
"    border: 2px solid #222222;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 16px;\n"
"    color: #eeeeee;\n"
"    selection-background-color: #00ff99;\n"
"    transition: all 2s ease-in-out;\n"
"}\n"
"\n"
"/* Hover effect: sleek green outline */\n"
"QLineEdit:hover {\n"
"    border: 2px solid #00cc66;\n"
"}\n"
"\n"
"/* Focus effect: sharp green glow */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00ff88;\n"
"    box-shadow: 0 0 6px #00ff88;\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    outline: none;\n"
"}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(490, 670, 421, 41))
        self.radioButton.setStyleSheet("QRadioButton {\n"
"text-align: center;\n"
"color: #222222;\n"
"}")
        self.radioButton.setObjectName("radioButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 710, 191, 81))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1280, 0, 91, 81))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 20, 131, 41))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    font-size: 25px;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 10, 121, 61))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 10, 121, 61))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #004720;\n"
"      color: white;\n"
"     padding: 5px 10px;\n"
"     margin: 8px 0;\n"
"    border: none;\n"
"    cursor: pointer;\n"
"    width: 100%;\n"
"    opacity: 0.9;\n"
"    border-radius: 15px;\n"
"    border: 1.5px solid #222222;\n"
"    font-size: 20px;\n"
"    color: #C8C8C8;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #00431F;\n"
"color: #e1e1e1;\n"
"border: 1.5px solid #858585;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(540, 640, 321, 31))
        self.lineEdit_7.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    opacity: 0.5;\n"
"    border-radius: 15px;\n"
"    padding: 6px 12px;\n"
"    font-size: 16px;\n"
"    color: #ff0000;\n"
"    selection-background-color: #00ff99;\n"
"    transition: all 2s ease-in-out;\n"
"}\n"
"\n"
"/* Focus effect: sharp green glow */\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00ff88;\n"
"    box-shadow: 0 0 6px #00ff88;\n"
"    background-color: #1a1a1a;\n"
"    color: #ffffff;\n"
"    outline: none;\n"
"}")
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setPlaceholderText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1513, 21))
        self.menubar.setObjectName("menubar")
        self.menuHello = QtWidgets.QMenu(self.menubar)
        self.menuHello.setObjectName("menuHello")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegistration = QtWidgets.QAction(MainWindow)
        self.actionRegistration.setObjectName("actionRegistration")
        self.menubar.addAction(self.menuHello.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Your FullName"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter Your Nickname"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Enter Your Balance"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:28pt; font-weight:600;\">Registration Form</span></p></body></html>"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Enter Your Age"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Enter Your Password"))
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Confirm Your Password"))
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Password)
        self.radioButton.setText(_translate("MainWindow", "გაეცანით Terms of Services და თანხმობის შემთხვევაში მონიშნეთ ღილაკი."))
        self.pushButton.setText(_translate("MainWindow", "Register"))
        self.pushButton_2.setText(_translate("MainWindow", "Login"))
        self.pushButton_3.setText(_translate("MainWindow", "𝐎𝐑𝐎𝐒𝐍𝐄𝐁𝐈"))
        self.pushButton_4.setText(_translate("MainWindow", "Blackjack"))
        self.pushButton_5.setText(_translate("MainWindow", "Baccarat"))
        self.menuHello.setTitle(_translate("MainWindow", "Registration"))
        self.actionRegistration.setText(_translate("MainWindow", "Registration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())